stages:
  data_ingestion:
    cmd: python "1. data-versioning/src/data_ingestion.py"
    deps:
    - 1. data-versioning/src/data_ingestion.py
    outs:
    - data/raw
  data_preprocessing:
    cmd: python "1. data-versioning/src/pre_process.py"
    deps:
    - 1. data-versioning/src/pre_process.py
    - data/raw
    outs:
    - data/processed
  feature_engineering:
    cmd: python "1. data-versioning/src/feature_engineering.py"
    deps:
    - 1. data-versioning/src/feature_engineering.py
    - data/processed
    outs:
    - data/features
